# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capital', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countrydata.Continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
