# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170211_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highscore', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='highscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='player',
        ),
        migrations.DeleteModel(
            name='Highscore',
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together=set([('player', 'game')]),
        ),
    ]
